/** Canonical Karachi delivery areas (A–Z). Used for seeding and reference. */
export const KARACHI_AREAS = [
  'Abdullah Goth',
  'Abul Hassan Isphahani Road',
  'Airport',
  'Akhtar Colony',
  'Al-Falah Society',
  'Al-Hilal Society',
  'Allah Wala Town',
  'Ancholi',
  'Ashraf Nagar',
  'Askari 1',
  'Askari 2',
  'Askari 3',
  'Askari 4',
  'Askari 5',
  'Ayesha Manzil',
  'Azam Basti',
  'Azam Town',
  'Babar Market',
  'Bachayo Narain',
  'Bagh e Korangi',
  'Bahadurabad',
  'Bahria Town Karachi',
  'Baldia Town',
  'Baloch Colony',
  'Banaras Colony',
  'Bandhani Colony',
  'Bath Island',
  'Baba Wilayat Shah Colony',
  'Beacon House',
  'Bhadur Colony',
  'Bhittaiabad',
  'Bihar Colony',
  'Bizm-e-Alam Society',
  'Block 1 Gulshan-e-Iqbal',
  'Block 2 Gulshan-e-Iqbal',
  'Block 3 Gulshan-e-Iqbal',
  'Block 4 Gulshan-e-Iqbal',
  'Block 5 Gulshan-e-Iqbal',
  'Block 6 Gulshan-e-Iqbal',
  'Block 7 Gulshan-e-Iqbal',
  'Block 8 Gulshan-e-Iqbal',
  'Block 9 Gulshan-e-Iqbal',
  'Block 10 Gulshan-e-Iqbal',
  'Block 11 Gulshan-e-Iqbal',
  'Block 12 Gulshan-e-Iqbal',
  'Block 13 Gulshan-e-Iqbal',
  'Block 14 Gulshan-e-Iqbal',
  'Block 15 Gulshan-e-Iqbal',
  'Block 16 Gulshan-e-Iqbal',
  'Block 17 Gulshan-e-Iqbal',
  'Block 18 Gulshan-e-Iqbal',
  'Bufferzone',
  'Burns Road',
  'Cantonment',
  'Chakra Goth',
  'Civil Lines',
  'Clifton Block 1',
  'Clifton Block 2',
  'Clifton Block 3',
  'Clifton Block 4',
  'Clifton Block 5',
  'Clifton Block 6',
  'Clifton Block 7',
  'Clifton Block 8',
  'Clifton Block 9',
  'DHA Phase 1',
  'DHA Phase 2',
  'DHA Phase 2 Extension',
  'DHA Phase 4',
  'DHA Phase 5',
  'DHA Phase 5 Extension',
  'DHA Phase 6',
  'DHA Phase 7',
  'DHA Phase 8',
  'Darakhshan Society',
  'Darul Aman Society',
  'Dastagir',
  'Defence View',
  'Delhi Colony',
  'Dhoraji Colony',
  'Do Talwar',
  'Drigh Road',
  'Eid Gah',
  'F.B. Area Block 1',
  'F.B. Area Block 2',
  'F.B. Area Block 3',
  'F.B. Area Block 4',
  'F.B. Area Block 5',
  'F.B. Area Block 6',
  'F.B. Area Block 7',
  'F.B. Area Block 8',
  'F.B. Area Block 9',
  'F.B. Area Block 10',
  'F.B. Area Block 11',
  'F.B. Area Block 12',
  'F.B. Area Block 13',
  'F.B. Area Block 14',
  'F.B. Area Block 15',
  'F.B. Area Block 16',
  'F.B. Area Block 17',
  'F.B. Area Block 18',
  'F.B. Area Block 19',
  'F.B. Area Block 20',
  'F.B. Area Block 21',
  'Faisal Cantonment',
  'Farooq-e-Azam',
  'Federal B Area',
  'Frere Town',
  'Garden East',
  'Garden West',
  'Gharibabad',
  'Gizri',
  'Gizri Boulevard',
  'Gulbahar',
  'Gulberg',
  'Gulistan-e-Johar Block 1',
  'Gulistan-e-Johar Block 2',
  'Gulistan-e-Johar Block 3',
  'Gulistan-e-Johar Block 4',
  'Gulistan-e-Johar Block 5',
  'Gulistan-e-Johar Block 6',
  'Gulistan-e-Johar Block 7',
  'Gulistan-e-Johar Block 8',
  'Gulistan-e-Johar Block 9',
  'Gulistan-e-Johar Block 10',
  'Gulistan-e-Johar Block 11',
  'Gulistan-e-Johar Block 12',
  'Gulistan-e-Johar Block 13',
  'Gulistan-e-Johar Block 14',
  'Gulistan-e-Johar Block 15',
  'Gulistan-e-Johar Block 16',
  'Gulistan-e-Johar Block 17',
  'Gulistan-e-Johar Block 18',
  'Gulistan-e-Johar Block 19',
  'Gulshan-e-Hadeed',
  'Gulshan-e-Iqbal',
  'Gulshan-e-Jamal',
  'Gulshan-e-Maymar',
  'Gulzar-e-Hijri',
  'Habib Bank Plaza',
  'Hajiyani Goth',
  'Harbour Front',
  'Hill Park',
  'Holy Family',
  'Hussainabad',
  'Hyderi',
  'I.I. Chundrigar Road',
  'Ibrahim Hyderi',
  'Jamshed Quarters',
  'Jauhar Chowrangi',
  'Jinnah Terminal',
  'Johar Complex',
  'KDA Scheme 1',
  'KDA Scheme 33',
  'Keamari',
  'Kehkashan',
  'Khadda Market',
  'Kharadar',
  'Khudadad Colony',
  'Korangi',
  'Korangi Crossing',
  'Korangi Industrial Area',
  'Korangi Sector 31',
  'Korangi Sector 32',
  'Korangi Sector 33',
  'Korangi Sector 34',
  'Korangi Sector 35',
  'Korangi Sector 36',
  'Landhi',
  'Liaquatabad',
  'Lines Area',
  'Lyari',
  'Malir',
  'Malir Cantonment',
  'Malir Halt',
  'Manzoor Colony',
  'Maripur',
  'Mehmoodabad',
  'Metroville',
  'Millat Nagar',
  'Model Colony',
  'Moinabad',
  'Mujahid Colony',
  'Muslimabad',
  'Muslim Town',
  'National Stadium',
  'Nazimabad 1',
  'Nazimabad 2',
  'Nazimabad 3',
  'Nazimabad 4',
  'Nazimabad 5',
  'Nazimabad 6',
  'Nazimabad 7',
  'New Karachi',
  'New Town',
  'Nishat Commercial',
  'North Karachi',
  'North Nazimabad Block A',
  'North Nazimabad Block B',
  'North Nazimabad Block C',
  'North Nazimabad Block D',
  'North Nazimabad Block E',
  'North Nazimabad Block F',
  'North Nazimabad Block G',
  'North Nazimabad Block H',
  'North Nazimabad Block I',
  'North Nazimabad Block J',
  'North Nazimabad Block K',
  'North Nazimabad Block L',
  'North Nazimabad Block M',
  'North Nazimabad Block N',
  'North Nazimabad Block O',
  'North Nazimabad Block P',
  'North Nazimabad Block Q',
  'North Nazimabad Block R',
  'North Nazimabad Block S',
  'North Nazimabad Block T',
  'Old Town',
  'Orangi Town',
  'P.E.C.H.S Block 1',
  'P.E.C.H.S Block 2',
  'P.E.C.H.S Block 3',
  'P.E.C.H.S Block 4',
  'P.E.C.H.S Block 5',
  'P.E.C.H.S Block 6',
  'Pakistan Chowk',
  'Paposh Nagar',
  'Paradise Point',
  'Patel Para',
  'Pechs',
  'PNS Karsaz',
  'Port Qasim',
  'Qayyumabad',
  'Railway Colony',
  'Ranchore Line',
  'Rashid Minhas Road',
  'Rehmani Goth',
  'Rizvia Society',
  'Saddar',
  'Safoora Goth',
  'Sakhi Hassan',
  'Shah Faisal Colony',
  'Shah Latif Town',
  'Shahrah-e-Faisal',
  'Shahrah-e-Quaideen',
  'Sharafi Goth',
  'Sharfabad',
  'Shepherd Street',
  'Shipowner College',
  'Sindhi Muslim Society',
  'Sohrab Goth',
  'Soldier Bazaar',
  'Star Gate',
  'Steel Town',
  'Super Highway',
  'Surjani Town',
  'Tariq Road',
  'Tipu Sultan Road',
  'University Road',
  'Water Pump',
  'Yaseenabad',
  'Zamzama',
  'Ziauddin Hospital',
]

export function areaSlug(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
    .slice(0, 80)
}

export function areaIdFromName(name) {
  return `da_${areaSlug(name)}`
}
